apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-deployment
  labels:
    app: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
      annotations:
        newrelic.com/integrations-sidecar-configmap: my-config
        newrelic.com/integrations-sidecar-imagename: newrelic/k8s-nri-nginx
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command:
          - sleep
          - "3600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: default
data:
  config.yaml: |
    integration_name: com.newrelic.nginx
    instances:
      - name: nginx-server-metrics
        command: metrics
        arguments:
          status_url: http://127.0.0.1/status
