apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-newrelic-integrations-config
  namespace: default
data:
  config.yaml: |
    integration_name: com.newrelic.apache
    instances:
        - name: apache-server-metrics
          command: metrics
          arguments:
              status_url: http://127.0.0.1/server-status?auto
              # New users should leave this property as `true`, to identify the
              # monitored entities as `remote`. Setting this property to `false` (the
              # default value) is deprecated and will be removed soon, disallowing
              # entities that are identified as `local`.
              # Please check the documentation to get more information about local
              # versus remote entities:
              # https://github.com/newrelic/infra-integrations-sdk/blob/master/docs/entity-definition.md
              remote_monitoring: true
          labels:
              env: production
              role: load_balancer
  definition.yaml: |
    name: com.newrelic.apache
    description: Reports status and metrics for Apache server
    protocol_version: 2
    os: linux
    commands:
        metrics:
            command:
              - ./bin/nr-apache
              - --metrics
            interval: 15
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      annotations:
        newrelic.com/integrations-sidecar-configmap: "apache-newrelic-integrations-config"
        newrelic.com/integrations-sidecar-imagename: "newrelic/k8s-nri-apache"
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        volumeMounts:
          - name: apache-conf-volume
            mountPath: /usr/local/apache2/conf/httpd.conf
            subPath: apache.conf
      volumes:
        - name: apache-conf-volume
          configMap:
            name: apache-conf
            items:
            - key: apache.conf
              path: apache.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-conf
  namespace: default
data:
  apache.conf: |
    ServerRoot "/usr/local/apache2"
    Listen 80

    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authn_file_module modules/mod_authn_file.so
    LoadModule authn_core_module modules/mod_authn_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
    LoadModule authz_user_module modules/mod_authz_user.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule access_compat_module modules/mod_access_compat.so
    LoadModule auth_basic_module modules/mod_auth_basic.so
    LoadModule reqtimeout_module modules/mod_reqtimeout.so
    LoadModule filter_module modules/mod_filter.so
    LoadModule mime_module modules/mod_mime.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule env_module modules/mod_env.so
    LoadModule headers_module modules/mod_headers.so
    LoadModule setenvif_module modules/mod_setenvif.so
    LoadModule version_module modules/mod_version.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule status_module modules/mod_status.so
    LoadModule autoindex_module modules/mod_autoindex.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule status_module modules/mod_status.so

    LoadModule alias_module modules/mod_alias.so
    <IfModule unixd_module>
    User daemon
    Group daemon
    </IfModule>

    ServerAdmin you@example.com
    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <IfModule dir_module>
        DirectoryIndex index.html
    </IfModule>

    <Files ".ht*">
        Require all denied
    </Files>

    ErrorLog /proc/self/fd/2
    LogLevel warn

    <IfModule log_config_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
        LogFormat "%h %l %u %t \"%r\" %>s %b" common
        <IfModule logio_module>
          LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
        </IfModule>
        CustomLog /proc/self/fd/1 common
    </IfModule>

    <IfModule alias_module>
        ScriptAlias /cgi-bin/ "/usr/local/apache2/cgi-bin/"
    </IfModule>

    <IfModule cgid_module>
    </IfModule>

    <Directory "/usr/local/apache2/cgi-bin">
        AllowOverride None
        Options None
        Require all granted
    </Directory>

    <IfModule headers_module>
        RequestHeader unset Proxy early
    </IfModule>

    <IfModule mime_module>
        TypesConfig conf/mime.types

        AddType application/x-compress .Z
        AddType application/x-gzip .gz .tgz
    </IfModule>

    <IfModule proxy_html_module>
    Include conf/extra/proxy-html.conf
    </IfModule>

    <IfModule ssl_module>
    SSLRandomSeed startup builtin
    SSLRandomSeed connect builtin
    </IfModule>

    <Location "/server-status">
        SetHandler server-status
        Allow from 127.0.0.1 ::1
    </Location>
