apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-newrelic-integrations-config
  namespace: default
data:
  config.yaml: |
    integration_name: com.newrelic.consul

    instances:
      - name: consul
        command: all_data
        arguments:
          hostname: 127.0.0.1
          trust_server_certificate: true
        labels:
          env: production
          role: consul
  definition.yaml: |
    name: com.newrelic.consul
    description: Reports status and metrics for HashiCorp Consul service
    protocol_version: 2
    os: linux

    commands:
      all_data:
        command:
          - ./bin/nr-consul
        interval: 15
        prefix: config/consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      annotations:
        newrelic.com/integrations-sidecar-configmap: "consul-newrelic-integrations-config"
        newrelic.com/integrations-sidecar-imagename: "newrelic/k8s-nri-consul"
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: consul:1.5.2
