apiVersion: v1
kind: ConfigMap
metadata:
  name: couchbase-newrelic-integrations-config
  namespace: default
data:
  config.yaml: |
    integration_name: com.newrelic.couchbase

    instances:
      - name: couchbase
        command: all_data
        arguments:
          hostname: 127.0.0.1
          username: Administrator
          password: password
        labels:
          env: production
          role: couchbase

  definition.yaml: |
    name: com.newrelic.couchbase
    description: Reports status and metrics for Couchbase service
    protocol_version: 2
    os: linux

    commands:
      all_data:
        command:
          - ./bin/nr-couchbase
        interval: 15
        prefix: config/couchbase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-deployment
  labels:
    app: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      annotations:
        newrelic.com/integrations-sidecar-configmap: "couchbase-newrelic-integrations-config"
        newrelic.com/integrations-sidecar-imagename: "newrelic/k8s-nri-couchbase"
      labels:
        app: couchbase
    spec:
      containers:
      - name: couchbase
        image: couchbase/server-sandbox:6.0.1
