apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster.name: mycluster
    network.host: "0.0.0.0"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-node
spec:
  serviceName: es-sts
  replicas: 2
  template:
    metadata:
      annotations:
        newrelic.com/integrations-sidecar-configmap: "elasticsearch-newrelic-integrations-config"
        newrelic.com/integrations-sidecar-imagename: "newrelic/k8s-nri-elasticsearch"
      labels:
        app: es-cluster
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - name: elasticsearch
        image: elasticsearch:6.6.0
        resources:
          requests:
            memory: 1Gi
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-yml
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-yml
          configMap:
            name: es-config
            items:
                - key: elasticsearch.yml
                  path: elasticsearch.yml
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-newrelic-integrations-config
  namespace: default
data:
  config.yaml: |
    integration_name: com.newrelic.elasticsearch
    instances:
      - name: elasticsearch
        command: all
        arguments:
          cluster_environment: $HOSTNAME
          username: elasticsearch
          password: changeme
        labels:
          role: elasticsearch
  definition.yaml: |
    name: com.newrelic.elasticsearch
    description: Reports status and metrics for elasticsearch service
    protocol_version: 2
    os: linux

    commands:
      all:
        command:
          - ./bin/nr-elasticsearch
        prefix: config/elasticsearch
        interval: 15
      inventory:
        command:
          - ./bin/nr-elasticsearch
          - --inventory
        prefix: config/elasticsearch
        interval: 15
